---
title: Posgrados Instituto de Física
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Universidad de Antioquia
email: posgrados@gfif.udea.edu.co
baseurl: "/home"
#url: "127.0.0.1:4000" # the base hostname & protocol for your site
url: "https://institutodefisica.github.io" # the base hostname & protocol for your site

##################
#### HEROKU ######
################## 
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'TODO.md']


#########################
#### PAGE's Folder ######
######################### 
include: ["_pages"] # Folder included to allow Jekyll look inside

#########################
### Sidebar Category ####
######################### 

categories: [pregrado, posgrado, personal, curso, servicio]


#favicon
favicon: ./favicon.png
twitter_username: PosgradosUdeA
fb_username: PosgradosUdeAntioquia
permalink: post/:year/:month/:day/:title
markdown: kramdown
authors:
  Posgrados Instituto de Física:
    display_name: Facultad de Ciencias Exactas y Naturales
    email: posgrados@gfif.udea.edu.co
    fb: PosgradosUdeAntioquia
    twitter: PosgradosUdeA
